name: quran
description: A new Flutter project.

version: 1.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Packages
  http: ^1.2.0
  provider: ^6.1.2
  intl: any
  # UI & Animations
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2
  liquid_progress_indicator: ^0.4.0

  # Quran & Qiblah
  flutter_qiblah: ^3.0.3
  arabic_font: ^0.0.9

  # Audio
  audioplayers: ^5.2.1
  audioplayers_web: ^4.1.0
  audio_video_progress_bar: ^2.0.2

  # Location & Maps
  geolocator: ^11.0.0
  geolocator_web: ^3.0.0
  location: ^6.0.1
  location_web: any
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.0

  # Notifications & Background Work
  flutter_local_notifications: ^17.2.2
  workmanager: ^0.5.2

  # Permissions
  permission_handler: ^11.3.1

  # Storage
  shared_preferences: ^2.2.2
  shared_preferences_web: any

  # Launcher & Sharing
  url_launcher: ^6.2.5
  url_launcher_web: any
  share_plus: ^7.2.0   # REPLACEMENT for 'share' (deprecated)

  # Toasts & Loading
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.0

  # Others
  choice: ^2.3.1
  kf_drawer: ^1.2.1
  wakelock_plus: ^1.1.6  # REPLACEMENT for deprecated 'wakelock'
  adhan: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - data/data.json
    - data/tafseer.json
    - images/
    - assets/sound/
    - android/app/src/main/res/raw/

  fonts:
    - family: quran
      fonts:
        - asset: fonts/Al-QuranAlKareem.ttf
